---
- name: "GRIST | Set up directories"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0750"
  with_items:
    - "{{ grist_skeleton_paths }}"
  tags:
    - grist_configure
  become: true

- name: "GRIST | Write configuration files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ grist_config_path | expanduser | realpath  }}/{{ item  }}"
    mode: '0640'
  loop:
    - "docker-compose.yml"
    - "env.grist.conf"
  tags:
    - grist_configure
  